apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ncor5c66x-nodejs
  janus-idp.io/tekton: ncor5c66x-nodejs
  backstage.io/kubernetes-id: ncor5c66x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ncor5c66x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
