apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ncor5c66x-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ncor5c66x-nodejs 
  name: ncor5c66x-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ncor5c66x-nodejs 
